# TheWalls2: The Walls 2 plugin.
# Copyright (C) 2012  Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#  
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 
# general:
#   world: The Walls 2 world name
#   fallback-world: The world which players will teleported to if they log
#                into The Walls 2 world while a game is not in progress
#   disconnect-timer: The time (in seconds) during which an offline player can log
#                     back into the server and remain in the game
#   monsters: Whether or not to disable monsters
#   friendly-fire: Whether or not team killing (or attacking) is allowed
#   prize: The prize for winning The Walls 2
#          Possible values:
#          - none (no prize)
#          - item (prize-item)
#          - money (prize-money, requires Vault)
#   prize-item: The item prize for winning The Walls 2
#   prize-money: (Requires Vault)
#                The money prize for winning The Walls 2
# game:
#   virtual: Whether or not the game is simulated virtually instead of using redstone
#   notify: (Requires virtual to be true)
#           Whether or not to notify players at certain intervals about the
#           remaining time until the walls fall
#   notify-interval: (Requires notify and virtual to be true)
#                    The time (in minutes) in between notifying players
#                    about the remaining time
#   time: (Requires virtual to be true)
#         The time (in minutes) that it takes for the walls to fall
# locations:
#   lobby: Lobby location (empty = default)
#          Format: x;y;z
#          Example: 250.5;65;100.5
# timer:
#   enabled: Whether or not the timer for starting games automatically is enabled
#   initial-time: The time (in minutes) that it takes after the server is started until
#                 a new game is started (if there are enough players)
#   normal-time: The time (in minutes) that it takes after the last game has finished
#                until a new game is started (if there are enough players)

general:
  world: thewalls2
  fallback-world: world
  disconnect-timer: 30
  monsters: false
  friendly-fire: false
  prize: item
  prize-item: '264:0:1'
  prize-money: 300.0
game:
  virtual: true
  notify: true
  notify-interval: 5
  time: 35
locations:
  lobby: ''
timer:
  enabled: true
  initial-time: 10
  normal-time: 15
