name: TheWalls2
main: me.Hoot215.TheWalls2.TheWalls2
version: 1.7.2
author: Hoot215
softdepend: [Vault]
website: 'http://dev.bukkit.org/server-mods/thewalls2/'
permissions:
    thewalls2.*:
        description: "Gives access to everything in TheWalls2"
        default: op
        children:
            thewalls2.default: true
            thewalls2.notify: true
            thewalls2.command.thewalls.start: true
            thewalls2.command.thewalls.stop: true
            thewalls2.command.thewalls.restoreworld: true
    thewalls2.default:
        description: "Gives access to defaults in TheWalls2"
        default: true
        children:
            thewalls2.command.thewalls: true
            thewalls2.command.thewalls.join: true
            thewalls2.command.thewalls.leave: true
            thewalls2.command.thewalls.team: true
    thewalls2.notify:
        description: "Receive notifications of plugin updates"
    thewalls2.command.thewalls:
        description: "Gives access to the command '/thewalls'"
    thewalls2.command.thewalls.join:
        description: "Gives access to the command '/thewalls join'"
    thewalls2.command.thewalls.leave:
        description: "Gives access to the command '/thewalls leave'"
    thewalls2.command.thewalls.team:
        description: "Gives access to the command '/thewalls team <1-4>'"
    thewalls2.command.thewalls.start:
        description: "Gives access to the command '/thewalls start'"
    thewalls2.command.thewalls.stop:
        description: "Gives access to the command '/thewalls stop'"
    thewalls2.command.thewalls.restoreworld:
        description: "Gives access to the command '/thewalls restoreworld'"
commands:
    thewalls:
        description: "Displays TheWalls2 help"
        permission: thewalls2.command.thewalls
        permission-message: "You don't have <permission>"
        usage: "/thewalls [Sub-Command]"
        aliases: [tw, twalls]